### ISSUE TITLE
OASIS Admin: Reports view from dashboard does not work

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#237]
## How to reproduce this
AS an admin user navigate to admin dashboard and press Reports link.

## Error logs
```
…
I, [2018-09-28T10:40:07.003881 #2254]  INFO -- : [b9a683e6-5e55-43ea-a68b-9760920e895c] Completed 401 Unauthorized in 110ms (Act
iveRecord: 14.9ms)
F, [2018-09-28T10:40:07.005671 #2254] FATAL -- : [b9a683e6-5e55-43ea-a68b-9760920e895c]
F, [2018-09-28T10:40:07.005726 #2254] FATAL -- : [b9a683e6-5e55-43ea-a68b-9760920e895c] ActionView::Template::Error (undefined m
ethod `[]' for nil:NilClass):
F, [2018-09-28T10:40:07.005839 #2254] FATAL -- : [b9a683e6-5e55-43ea-a68b-9760920e895c]      6:   <p><%= link_to "View top 5", h
yrax.admin_stats_path %> </p>
[b9a683e6-5e55-43ea-a68b-9760920e895c]      7: <% end %>
[b9a683e6-5e55-43ea-a68b-9760920e895c]      8:
[b9a683e6-5e55-43ea-a68b-9760920e895c]      9: <h3>Top File Formats (top <%= @presenter.top_formats.count %>)</h3>
[b9a683e6-5e55-43ea-a68b-9760920e895c]     10: <ul>
[b9a683e6-5e55-43ea-a68b-9760920e895c]     11:   <% @presenter.top_formats.each do |fmt| %>
[b9a683e6-5e55-43ea-a68b-9760920e895c]     12:     <li><%= fmt.label %> <span class="count">(<%= fmt.value %>)</span></li>
F, [2018-09-28T10:40:07.005872 #2254] FATAL -- : [b9a683e6-5e55-43ea-a68b-9760920e895c]
F, [2018-09-28T10:40:07.005934 #2254] FATAL -- : [b9a683e6-5e55-43ea-a68b-9760920e895c] vendor/bundle/ruby/2.5.0/gems/hyrax-2.0.1/app/services/hyrax/statistics/term_query.rb:33:in `query'
[b9a683e6-5e55-43ea-a68b-9760920e895c] vendor/bundle/ruby/2.5.0/gems/hyrax-2.0.1/app/services/hyrax/statistics/term_query.rb:12:in `query'
[b9a683e6-5e55-43ea-a68b-9760920e895c] vendor/bundle/ruby/2.5.0/gems/hyrax-2.0.1/app/presenters/hyrax/admin_stats_presenter.rb:44:in `top_formats’
...
```

**Comment by yf508** [comment]
This is not a new bug. It's not working from the beginning - maybe some settings missing.

**Comment by yf508** [comment]
For Google Analytics settings, check:

https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#analytics-and-usage-statistics
